# Generated by Django 3.2.12 on 2022-03-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
